- project-1/src/main/java/com/kosmo/springapp/controller/LoginController.java
> 0703-쿠키가 담기지 않는 에러 해결

- project-1/src/main/webapp/WEB-INF/views/template/Top.jsp
> Index taeseung

- project-1/src/main/webapp/WEB-INF/views/Index.jsp
- project-1/src/main/webapp/WEB-INF/views/template/Top.jsp
비디오 파일 추가하며
탑 바텀에 div= main을 주며 마진탑50px로 전체적인 바디가 하향배치함
> 0704 - main index 비디오적용

- project-1/src/main/webapp/WEB-INF/views/nutrient_select/Nutrient_Select01.jsp
- project-1/src/main/webapp/WEB-INF/views/nutrient_select/Nutrient_Select02.jsp
> 0705 - 영양소 선택 페이지 추가

- project-1/src/main/resources/static/tsfolder/css/style.css
- project-1/src/main/webapp/WEB-INF/views/Index.jsp
> 0705 - 메인 사이드바 수정

- project-1/src/main/webapp/WEB-INF/views/Index.jsp
> 0705 - 로그인 설정

- project-1/src/main/webapp/WEB-INF/views/template/Top.jsp
> 0705 - 탑 수정

- project-1/src/main/webapp/WEB-INF/views/Index.jsp
인덱스에 로그인 버튼 및 로그인 기능으로 넘어가는 거 추가함
> 0705 - index에 로그인 기능 추가

- project-1/src/main/webapp/WEB-INF/views/Index.jsp
> 0706 - 사이드 로그인 수정

- project-1/src/main/webapp/WEB-INF/views/Index.jsp
- project-1/src/main/webapp/WEB-INF/views/template/Top.jsp
> 0706 - top, index 수정

- project-1/src/main/webapp/WEB-INF/views/Index.jsp
- project-1/src/main/webapp/WEB-INF/views/template/Top.jsp
> 0706 - c: url 작업함

- project-1/src/main/webapp/WEB-INF/views/template/Top.jsp
> 0706 - 기다려모두!

- project-1/src/main/webapp/WEB-INF/views/Index.jsp
- project-1/src/main/webapp/WEB-INF/views/template/Footer.jsp
- project-1/src/main/webapp/WEB-INF/views/template/Top.jsp
> 0706 - 메인 탑 푸터

- project-1/src/main/webapp/WEB-INF/views/Index.jsp
- project-1/src/main/webapp/WEB-INF/views/template/Top.jsp
> 0706 - 글씨체 ㅁ바꿈

- project-1/src/main/resources/static/tsfolder/css/style.css
- project-1/src/main/webapp/WEB-INF/views/Index.jsp
- project-1/src/main/webapp/WEB-INF/views/ListTable.jsp
- project-1/src/main/webapp/WEB-INF/views/template/Footer.jsp
- project-1/src/main/webapp/WEB-INF/views/template/Top.jsp
> 0706 - 탑 푸터 인덱스

- project-1/src/main/resources/static/tsfolder/js/main.js
- project-1/src/main/webapp/WEB-INF/views/Index.jsp
> 0706 - 상단 사이드바 밀림 함수 적용

- project-1/src/main/resources/static/tsfolder/css/style.css
- project-1/src/main/resources/static/tsfolder/js/main.js
- project-1/src/main/webapp/WEB-INF/views/Index.jsp
- project-1/src/main/webapp/WEB-INF/views/template/Footer.jsp
- project-1/src/main/webapp/WEB-INF/views/template/Top.jsp
전체화면으로 표출
동영상 오늘 하루 그만 보기 누르면
오늘 하루동안 나오지 않음.
> 0707 - 메인 동영상 표출

- project-1/src/main/resources/static/tsfolder/css/style.css
- project-1/src/main/webapp/WEB-INF/views/Index.jsp
- project-1/src/main/webapp/WEB-INF/views/template/Top.jsp
> 0707 - 인덱스 배너 수정중

- project-1/src/main/webapp/WEB-INF/views/template/Top.jsp
> 0707 - 동영상

- project-1/src/main/webapp/WEB-INF/views/Index.jsp
- project-1/src/main/webapp/WEB-INF/views/template/Top.jsp
동영상 수정하며
스크립트 로직을 추가하여
오늘 하루보지 않기를 눌렀을 때
현재시간과 다음날 자정이 되는 시간을 계산하여 체크시 안나오고 다음날이 되면 체크가 풀릴 수 있는 로직을 만듬
> 0708 - 악성동영상 수정

- project-1/src/main/resources/static/tsfolder/css/style.css
- project-1/src/main/resources/static/tsfolder/js/main.js
- project-1/src/main/webapp/WEB-INF/views/Index.jsp
배너는 차차 수정하도록 하며
버튼을 누를 때 화면 넘어갈 수 있는 배너를 만듬
> 0709 - mainindex 마무리

- project-1/src/main/resources/static/tsfolder/js/TSmain.js
- project-1/src/main/webapp/WEB-INF/views/slider/MagazineIndex.jsp
일단 1차적인 마무리 후 스타일 부분 조정은 다른 페이지와 맞춰보기
> 0709 - 메거진 수정

- project-1/src/main/java/com/kosmo/springapp/nutrient/controller/NutrientController.java
- project-1/src/main/java/com/kosmo/springapp/nutrient/service/NutrientSelectService.java
- project-1/src/main/java/com/kosmo/springapp/nutrient/service/impl/NutrientSelectMapper.java
- project-1/src/main/java/com/kosmo/springapp/nutrient/service/impl/NutrientSelectServiceImpl.java
- project-1/src/main/resources/mybatis/select.xml
- project-1/src/main/webapp/WEB-INF/views/nutrient/NutrientDetail.jsp
- project-1/src/main/webapp/WEB-INF/views/nutrient/NutrientSelect.jsp
> 0710 - 영양소 디테일 수정

- project-1/src/main/java/com/kosmo/springapp/nutrient/service/impl/NutrientSelectServiceImpl.java
- project-1/src/main/resources/mybatis/select.xml
- project-1/src/main/webapp/WEB-INF/views/nutrient/NutrientDetail.jsp
- project-1/src/main/webapp/WEB-INF/views/nutrient/NutrientSelect.jsp
> 0710 - 영양소 세부사항 수정

- project-1/src/main/webapp/WEB-INF/views/Index.jsp
지도 추가하여 검색창 지도까지 뜨지만 검색버튼이 작동하지 않음
> 0711 - 메인 지도 추가

- project-1/src/main/webapp/WEB-INF/views/Index.jsp
> 0711 - 메인 바디 다이브 추가

- project-1/src/main/java/com/kosmo/springapp/nutrient/service/impl/NutrientSelectServiceImpl.java
- project-1/src/main/webapp/WEB-INF/views/nutrient/NutrientDetail.jsp
> 0711 - 세부사항 및 진행바 완료

- project-1/src/main/webapp/WEB-INF/views/Index.jsp
- project-1/src/main/webapp/WEB-INF/views/template/Top.jsp
> 0711 - 메인 5div 만듬

- project-1/src/main/webapp/WEB-INF/views/template/Top.jsp
> 0711 - top

- project-1/src/main/webapp/WEB-INF/views/Index.jsp
> 0711 - 메인 수정

- project-1/src/main/java/com/kosmo/springapp/nutrient/controller/NutrientController.java
- project-1/src/main/java/com/kosmo/springapp/nutrient/service/N_FoodTableDTO.java
- project-1/src/main/java/com/kosmo/springapp/nutrient/service/NutrientSelectService.java
- project-1/src/main/java/com/kosmo/springapp/nutrient/service/impl/NutrientSelectMapper.java
- project-1/src/main/resources/mybatis/select.xml
- project-1/src/main/webapp/WEB-INF/views/nutrient/NutrientDetail.jsp
- project-1/src/main/webapp/WEB-INF/views/nutrient/NutrientSelect.jsp
> 0712 - 검색창 만들고 추천 영양제

- project-1/src/main/resources/static/tsfolder/css/style.css
- project-1/src/main/webapp/WEB-INF/views/Index.jsp
- project-1/src/main/webapp/WEB-INF/views/login/Login.jsp
- project-1/src/main/webapp/WEB-INF/views/slider/MagazineIndex.jsp
로그인 자스랑 css 추가하여 수정하고
스타일 메거진 조금 수정함
> 0712 - 로그인 css 수정

- project-1/src/main/resources/static/tsfolder/css/style.css
> 0713 - 반응형 상단배너수정

- project-1/src/main/webapp/WEB-INF/views/login/Login.jsp
> 0713 - 로그인페이지 수정

- project-1/src/main/java/com/kosmo/springapp/controller/SelectFoodRankListController.java
- project-1/src/main/java/com/kosmo/springapp/service/SelectFoodMapper.java
- project-1/src/main/java/com/kosmo/springapp/service/SelectFoodService.java
- project-1/src/main/java/com/kosmo/springapp/service/impl/SelectFoodServiceImpl.java
- project-1/src/main/resources/mybatis/selectfunctionfood.xml
- project-1/src/main/webapp/WEB-INF/views/Index.jsp
- project-1/src/main/webapp/WEB-INF/views/ranking/FoodRank.jsp
- project-1/src/main/webapp/WEB-INF/views/template/SelectFoodListStyleScript.jsp
> 0713-건기식 입력해서 찾기1차

- project-1/src/main/resources/static/tsfolder/css/style.css
- project-1/src/main/webapp/WEB-INF/views/Index.jsp
> 0714 - 메인 배너 수정

- project-1/src/main/java/com/kosmo/springapp/controller/HelloSpringController.java
- project-1/src/main/java/com/kosmo/springapp/controller/SelectFoodRankListController.java
- project-1/src/main/webapp/WEB-INF/views/Index.jsp
> 0714-메인페이지 제품추천으로 띄우기

- project-1/src/main/webapp/WEB-INF/views/Index.jsp
> 0714-오른쪽움직이는 사이드바 내용변경

- project-1/src/main/webapp/WEB-INF/views/slider/Magazine01.jsp
- project-1/src/main/webapp/WEB-INF/views/slider/Magazine02.jsp
- project-1/src/main/webapp/WEB-INF/views/slider/Magazine04.jsp
- 이미지 추가 및 코드 추가 작성
- CSS 전체 수정완료
> 0714 - magazine04 수정

- project-1/src/main/java/com/kosmo/springapp/qnabbs/controller/BoardController.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/service/DaoService.java
- project-1/src/main/resources/mybatis/board.xml
- project-1/src/main/webapp/WEB-INF/views/Index.jsp
- project-1/src/main/webapp/WEB-INF/views/board/Edit.jsp
- project-1/src/main/webapp/WEB-INF/views/board/List.jsp
- project-1/src/main/webapp/WEB-INF/views/board/View.jsp
- project-1/src/main/webapp/WEB-INF/views/board/Write.jsp
> 0715 qnabbs

- project-1/src/main/resources/static/tsfolder/css/style.css
- project-1/src/main/resources/static/tsfolder/js/mainjs.js
- project-1/src/main/webapp/WEB-INF/views/Index.jsp
> 0716 - 메인 칼럼 수정

- project-1/src/main/webapp/WEB-INF/views/template/Top.jsp
> 0716 - 탑 링크수정

- project-1/src/main/java/com/kosmo/springapp/qnabbs/controller/BoardController.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/service/DaoService.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/service/impl/board/BoardServiceImpl.java
- project-1/src/main/resources/mybatis/board.xml
- project-1/src/main/webapp/WEB-INF/views/board/List.jsp
> qnabbs - 페이징 처리

- project-1/src/main/webapp/WEB-INF/views/Detail.jsp
> 0718 - 상단 배너 위치조정

- project-1/src/main/webapp/WEB-INF/views/AnalyzeNewReport.jsp
값이 한개라도 없으면 분석하기 버튼을 비활성화 하고 값들이 다 입력되면 버튼이 활성화 됨
> 0718 - 분석 리포트 유효성검사

- project-1/src/main/java/com/kosmo/springapp/analyze/controller/ResultController.java
- project-1/src/main/java/com/kosmo/springapp/analyze/service/AnalyzeMapper.java
- project-1/src/main/java/com/kosmo/springapp/analyze/service/AnalyzeService.java
- project-1/src/main/java/com/kosmo/springapp/analyze/service/impl/AnalyzeServiceImpl.java
- project-1/src/main/java/com/kosmo/springapp/service/impl/AnalyzeMyReportServiceImpl.java
- project-1/src/main/resources/mybatis/analyze.xml
- project-1/src/main/webapp/WEB-INF/views/test1.jsp
> 0720-기능성점수 50점이한계 등등

- project-1/src/main/webapp/WEB-INF/views/template/Top.jsp
> 0721 - 탑 수정

- project-1/src/main/java/com/kosmo/springapp/qnabbs/controller/AnswerBoardController.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/controller/BoardController.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/service/AnswerService.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/service/impl/board/AnswerServiceImpl.java
- project-1/src/main/resources/mybatis/answerboard.xml
- project-1/src/main/webapp/WEB-INF/views/board/AnswerEdit.jsp
- project-1/src/main/webapp/WEB-INF/views/board/View.jsp
수정까지 가능, 답글이 없는 글만 삭제 가능, 답글 있을 시 삭제 불가
> qnabbs/answer editProcess

- project-1/src/main/resources/static/tsfolder/css/style.css
- project-1/src/main/resources/static/tsfolder/js/mainjs.js
- project-1/src/main/webapp/WEB-INF/views/Index.jsp
> 0724 - 메인 수정

- project-1/src/main/java/com/kosmo/springapp/qnabbs/controller/AnswerBoardController.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/controller/BoardController.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/service/impl/board/AnswerServiceImpl.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/service/impl/board/BoardServiceImpl.java
- project-1/src/main/resources/mybatis/answerboard.xml
- project-1/src/main/webapp/WEB-INF/views/board/View.jsp
질문 글 삭제 시 답변 글이 있어도 삭제 가능
아직 답변 글 삭제 불가
> qnabbs/질문글- 답변글이 있어도 삭제 가능

- project-1/src/main/java/com/kosmo/springapp/qnabbs/controller/AnswerBoardController.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/controller/AnswerBoardRestController.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/controller/BoardController.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/service/AnswerService.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/service/impl/board/AnswerMapper.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/service/impl/board/AnswerServiceImpl.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/service/impl/board/BoardServiceImpl.java
- project-1/src/main/resources/mybatis/answerboard.xml
- project-1/src/main/resources/mybatis/board.xml
- project-1/src/main/webapp/WEB-INF/views/board/View.jsp
> qnabbs/삭제 처리

- project-1/src/main/webapp/WEB-INF/views/template/Top.jsp
> 0726 - 탑 토글바 생성

- project-1/src/main/java/com/kosmo/springapp/qnabbs/controller/AnswerBoardController.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/controller/BoardController.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/controller/LikeBoardController.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/service/AnswerService.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/service/LikeBoardService.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/service/impl/board/AnswerMapper.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/service/impl/board/AnswerServiceImpl.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/service/impl/board/BoardServiceImpl.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/service/impl/board/LikeBoardMapper.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/service/impl/board/LikeBoardServiceImpl.java
- project-1/src/main/resources/mybatis/answerboard.xml
- project-1/src/main/resources/mybatis/board.xml
- project-1/src/main/resources/mybatis/likeboard.xml
- project-1/src/main/webapp/WEB-INF/views/board/AnswerEdit.jsp
- project-1/src/main/webapp/WEB-INF/views/board/AnswerWrite.jsp
- project-1/src/main/webapp/WEB-INF/views/board/List.jsp
- project-1/src/main/webapp/WEB-INF/views/board/View.jsp
> 0727 - qnabbs좋아요 기능 완성

- project-1/src/main/java/com/kosmo/springapp/qnabbs/controller/BoardController.java
> 0729 - qnabbs View.jsp수정

- project-1/src/main/java/com/kosmo/springapp/controller/HelloSpringController.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/controller/AnswerBoardController.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/controller/BoardController.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/controller/LikeBoardController.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/service/impl/board/BoardServiceImpl.java
- project-1/src/main/resources/config/paging.properties
- project-1/src/main/resources/mybatis/answerboard.xml
- project-1/src/main/resources/mybatis/board.xml
- project-1/src/main/webapp/WEB-INF/views/Index.jsp
- project-1/src/main/webapp/WEB-INF/views/board/List.jsp
- project-1/src/main/webapp/WEB-INF/views/board/View.jsp
> 0730 - qnabbs 페이징 수정

- project-1/src/main/java/com/kosmo/springapp/qnabbs/controller/LikeBoardController.java
- project-1/src/main/webapp/WEB-INF/views/board/List.jsp
- project-1/src/main/webapp/WEB-INF/views/board/View.jsp
qnabbs View.jsp와 boardController js수정
> 0731 - qnabbs 비회원 좋아요 알람으로 수정

- project-1/src/main/webapp/WEB-INF/views/board/Edit.jsp
- project-1/src/main/webapp/WEB-INF/views/board/View.jsp
- project-1/src/main/webapp/WEB-INF/views/board/Write.jsp
> 0731 - qnabbs css미완 수정

- project-1/src/main/java/com/kosmo/springapp/qnabbs/controller/BoardController.java
- project-1/src/main/java/com/kosmo/springapp/qnabbs/controller/LikeBoardController.java
- project-1/src/main/webapp/WEB-INF/views/board/AnswerEdit.jsp
- project-1/src/main/webapp/WEB-INF/views/board/AnswerWrite.jsp
- project-1/src/main/webapp/WEB-INF/views/board/Edit.jsp
- project-1/src/main/webapp/WEB-INF/views/board/View.jsp
- project-1/src/main/webapp/WEB-INF/views/board/Write.jsp
write, edit, answer_write, answer_edit의 부트스트랩 주석처리함
> 0731 - qnabbs 탑 햄버거 클릭용 부트스트랩 주석처리
